name: R-CMD-check

on:
  release:
    types: [published]

jobs:
  R-CMD-check:
    uses: r-lib/actions/.github/workflows/check-standard.yaml@v1
    with:
      r-versions: '4.3.0, 4.4.0, 4.4.3'
      os: 'ubuntu-latest, windows-latest, macos-latest'
